version: "3.7"

services:
  fom_api:
    image: fom_api_url:4.0
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      NUMBER_WORKERS: 10
      NUMBER_THREADS: 2
      TIMEOUT: 120
  webcam_api:
    image: webcamapp:2.0
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
  swap_api:
    image: simswap:1.0
    ports:
      - 5001:5001
    environment:
      NUMBER_PROCESSES: 10
      NUMBER_THREADS: 1
  celeb_class_api:
    image: celeb_class:2.0
    ports:
      - 5002:5002
    volumes:
      - ../../../mnt/d/big_dataset/Test:/app/volume
    networks:
      - mynetwork
    environment:
      NUMBER_WORKERS: 10
      NUMBER_THREADS: 4
  mongodb:
    image: mongo:latest
    container_name: test-mongo
    ports:
      - 27017:27017
    networks:
      - mynetwork
  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    networks:
      - mynetwork
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh

networks:
  mynetwork:
    driver: bridge